exclude: ^venv\/$
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: ["--check"]
        exclude: "^jobparser/(settings|middlewares|spiders/hhru).py$"

      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        args: ["--check", "--ignore-whitespace"]

      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        exclude: "^jobparser/(settings|middlewares|selectors).py$"